/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mkfractal;

import java.awt.Color;
import java.awt.Graphics;
import java.util.Random;
import javax.swing.JSlider;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.plaf.basic.BasicMenuUI;
import org.apache.commons.numbers.complex.Complex;

/**
 *
 * @author thorsten
 */
public class NewJFrame extends javax.swing.JFrame {

    NewJPanel p = new NewJPanel();

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        jSplitPane1.setLeftComponent(p);

        Complex c = p.pool[0].f(Complex.ofCartesian(0, 0));

        Random r = new Random();
        
        for (int i = 0; i < p.pool[0].r; ++i) {
            final int j = i;
            JSlider s = new JSlider(-1000, 1000, 0);
            s.addChangeListener(new ChangeListener() {
                @Override
                public void stateChanged(ChangeEvent ce) {
                    p.rands[j] = s.getValue() / 1000.0;
                    p.repaint();
                 }
            });
            jPanel2.add(s);
            s.setValue(r.nextInt(2000) - 1000);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(800, 600));

        jSplitPane1.setDividerLocation(600);

        jPanel2.setLayout(new java.awt.GridLayout(0, 1));
        jSplitPane1.setRightComponent(jPanel2);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
